### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by dominikwilkowski** [aral/fork-me-on-github-retina-ribbons#2]
When I visit https://aral.github.com/fork-me-on-github-retina-ribbons/right-white@2x.png I get redirected to the non-SSL HTTP version which means I can't use the ribbon without producing a mix-content warning on my secure site [all GH-pages now are SSL](https://github.com/blog/2186-https-for-github-pages).

I'd be great to support SSL as default for these.

**Comment by theel0ja** [comment]
Use https://aral.github.io/fork-me-on-github-retina-ribbons/right-white@2x.png
